version: "3"
services:
  laravel:
    build:
      context: ./laravel
    ports:
      - "80:8000"
    volumes:
      - "../laravel:/var/www"
    environment:
      - HOST
      - TZ
      - HTTP_PROXY
      - http_proxy
      - HTTPS_PROXY
      - https_proxy
      - FTP_PROXY
      - ftp_proxy

    tty: true


  db:
    image: mariadb:10.5
    ports:
    - "3306:3306"
    volumes:
    - "./db/data:/var/lib/mysql"
    - "./db/initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
