version: "3"
volumes:
  volume-node-modules:
  volume-db-data:
  volume-vendor:
services:
  laravel:
    build:
      context: ./laravel
    ports:
      - "80:8000"
    volumes:
      - "../laravel:/var/www"
      - "volume-node-modules:/var/www/node_modules"
      - "volume-vendor:/var/www/vendor"
    environment:
      - HOST
      - TZ

    tty: true


  db:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
